"""
Base classes for automation strategies.

These are simplified versions for the autopilot's strategy signals,
separate from the full backtesting strategy framework.
"""

from dataclasses import dataclass, field
from typing import Optional, Dict, Any, List
from enum import Enum
from abc import ABC, abstractmethod

from ..unified_controller import ForecastContext


class SignalType(str, Enum):
    """Trading signal type."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    symbol: str
    signal_type: SignalType
    weight: float = 1.0  # Signal strength 0-1
    confidence: float = 0.5  # Confidence in signal 0-1
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Forecast-adjusted fields
    forecast_adjusted: bool = False
    original_confidence: Optional[float] = None
    forecast_multiplier: float = 1.0


class BaseStrategy(ABC):
    """
    Abstract base for automation strategies.
    
    These strategies are simpler than the full backtesting framework,
    focused on generating signals from market data.
    """
    
    @property
    @abstractmethod
    def id(self) -> str:
        """Unique strategy identifier."""
        pass
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable name."""
        pass
    
    @property
    @abstractmethod
    def description(self) -> str:
        """Strategy description."""
        pass
    
    @abstractmethod
    async def calculate_signals(
        self, 
        market_data: Dict[str, Any],
        forecast_context: Optional[ForecastContext] = None
    ) -> List[StrategySignal]:
        """
        Calculate trading signals from market data.
        
        Args:
            market_data: Dict with 'symbol', 'formatted' (price data), etc.
            forecast_context: Optional forecast context for intelligent filtering
            
        Returns:
            List of strategy signals
        """
        pass
    
    def adjust_signal_with_forecast(
        self, 
        signal: StrategySignal, 
        forecast: ForecastContext
    ) -> Optional[StrategySignal]:
        """
        Adjust a signal based on forecast context.
        
        Returns None if signal should be filtered out.
        Returns adjusted signal otherwise.
        """
        # Check if signal aligns with forecast bias
        if signal.signal_type == SignalType.BUY:
            if forecast.bias.value == "bearish":
                # Reduce confidence for buys in bearish forecast
                signal.original_confidence = signal.confidence
                signal.confidence *= 0.5
                signal.forecast_adjusted = True
            elif forecast.bias.value == "bullish":
                # Boost confidence for buys in bullish forecast
                signal.original_confidence = signal.confidence
                signal.confidence = min(1.0, signal.confidence * 1.2)
                signal.forecast_adjusted = True
                
        elif signal.signal_type == SignalType.SELL:
            if forecast.bias.value == "bullish":
                signal.original_confidence = signal.confidence
                signal.confidence *= 0.5
                signal.forecast_adjusted = True
            elif forecast.bias.value == "bearish":
                signal.original_confidence = signal.confidence
                signal.confidence = min(1.0, signal.confidence * 1.2)
                signal.forecast_adjusted = True
        
        # Apply size multiplier from forecast
        signal.forecast_multiplier = forecast.size_multiplier
        signal.metadata["forecast_bias"] = forecast.bias.value
        signal.metadata["forecast_volatility"] = forecast.historical_volatility
        
        return signal
